version: '3.8'

services:
  rabbitmq:
      image: "rabbitmq:3-management"
      restart: always
      ports:
        - "15672:15672"
        - "5672:5672"
      volumes:
        - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
    driver: local